blank_issues_enabled: false
contact_links:
  - name: Frage / Diskussion
    url: https://github.com/Stieges/hallenfussball-pwa/discussions
    about: FÃ¼r allgemeine Fragen nutze bitte die Discussions
